#!/usr/bin/env python3
"""Validate JSON files against a JSON Schema.

Generated by Ananke CLI Tool Generator.
"""

import click
import json
import sys
from pathlib import Path
from typing import Optional

try:
    from jsonschema import validate, ValidationError
except ImportError:
    print("Error: jsonschema is required. Install with: pip install jsonschema", file=sys.stderr)
    sys.exit(2)


def validate_file_exists(file_path: str, file_type: str = "File") -> Path:
    """Validate that a file exists and is readable.

    Args:
        file_path: Path to the file to validate
        file_type: Type of file for error messages

    Returns:
        Path object if valid

    Raises:
        SystemExit: If file doesn't exist or isn't readable
    """
    path = Path(file_path)
    if not path.exists():
        click.echo(
            click.style("Error:", fg="red", bold=True) + f" {file_type} not found: {file_path}",
            err=True,
        )
        sys.exit(2)

    if not path.is_file():
        click.echo(
            click.style("Error:", fg="red", bold=True) + f" Not a file: {file_path}",
            err=True,
        )
        sys.exit(2)

    return path


def load_json_file(file_path: Path, file_type: str = "File") -> dict:
    """Load and parse a JSON file.

    Args:
        file_path: Path to the JSON file
        file_type: Type of file for error messages

    Returns:
        Parsed JSON data

    Raises:
        SystemExit: If JSON is malformed
    """
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        click.echo(
            click.style("Error:", fg="red", bold=True)
            + f" Invalid JSON in {file_path}: {e.msg} at line {e.lineno}, column {e.colno}",
            err=True,
        )
        sys.exit(2)
    except IOError as e:
        click.echo(
            click.style("Error:", fg="red", bold=True) + f" Cannot read {file_path}: {e}",
            err=True,
        )
        sys.exit(2)


@click.command()
@click.argument("json_file", type=click.Path())
@click.option(
    "--schema",
    "-s",
    required=True,
    type=click.Path(),
    help="Path to JSON Schema file",
)
@click.option(
    "--strict",
    is_flag=True,
    help="Enable strict validation mode (shows detailed error paths)",
)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    help="Enable verbose output",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    help="Output validation report to file (optional)",
)
def validate_json(
    json_file: str,
    schema: str,
    strict: bool,
    verbose: bool,
    output: Optional[str],
) -> None:
    """Validate JSON files against a JSON Schema.

    This command reads a JSON file and validates it against a provided
    JSON Schema file. Returns exit code 0 for valid files, 1 for validation
    failures, and 2 for runtime errors.

    Examples:

        # Basic validation
        validate data.json --schema schema.json

        # Strict mode with detailed error paths
        validate data.json --schema schema.json --strict

        # Short option syntax
        validate data.json -s schema.json -v

    Exit Codes:

        0 - JSON is valid according to schema
        1 - Validation failed
        2 - Runtime error (file not found, invalid JSON, etc.)
    """
    # Verbose logging
    if verbose:
        click.echo(f"Validating JSON file: {json_file}", err=True)
        click.echo(f"Using schema: {schema}", err=True)
        if strict:
            click.echo("Strict mode: enabled", err=True)

    # Validate files exist
    json_path = validate_file_exists(json_file, "JSON file")
    schema_path = validate_file_exists(schema, "Schema file")

    # Load JSON file
    if verbose:
        click.echo("Loading JSON file...", err=True)

    json_data = load_json_file(json_path, "JSON file")

    # Load schema file
    if verbose:
        click.echo("Loading schema file...", err=True)

    schema_data = load_json_file(schema_path, "Schema file")

    # Perform validation
    if verbose:
        click.echo("Validating...", err=True)

    try:
        validate(instance=json_data, schema=schema_data)

        # Validation successful
        success_msg = click.style("✓", fg="green", bold=True) + f" {json_file} is valid"
        click.echo(success_msg)

        # Write report if requested
        if output:
            report = {
                "status": "valid",
                "file": str(json_file),
                "schema": str(schema),
                "strict_mode": strict,
            }

            try:
                output_path = Path(output)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(report, f, indent=2)

                if verbose:
                    click.echo(f"Report written to: {output}", err=True)
            except IOError as e:
                click.echo(
                    click.style("Warning:", fg="yellow", bold=True)
                    + f" Cannot write report to {output}: {e}",
                    err=True,
                )

        sys.exit(0)

    except ValidationError as e:
        # Validation failed
        error_msg = click.style("✗", fg="red", bold=True) + f" Validation failed: {e.message}"
        click.echo(error_msg, err=True)

        if strict and e.path:
            path_str = ".".join(str(p) for p in e.path)
            click.echo(f"  Path: {path_str}", err=True)
            if e.schema_path:
                schema_path_str = ".".join(str(p) for p in e.schema_path)
                click.echo(f"  Schema path: {schema_path_str}", err=True)

        # Write error report if requested
        if output:
            report = {
                "status": "invalid",
                "file": str(json_file),
                "schema": str(schema),
                "error": e.message,
                "path": [str(p) for p in e.path] if e.path else [],
            }

            try:
                output_path = Path(output)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(report, f, indent=2)
            except IOError:
                pass  # Silent failure for error case

        sys.exit(1)


if __name__ == "__main__":
    validate_json()
