// Core constraint types for the Ananke system
const std = @import("std");

/// Unique identifier for constraints
pub const ConstraintID = u64;

/// Categories of constraints that can be extracted and enforced
pub const ConstraintKind = enum {
    syntactic, // Code structure, formatting, naming
    type_safety, // Type annotations, null safety, generics
    semantic, // Data flow, control flow, side effects
    architectural, // Module boundaries, dependencies, layering
    operational, // Performance, memory, concurrency
    security, // Input validation, auth, dangerous ops
};

/// Severity levels for constraint violations
pub const Severity = enum {
    err, // Must be fixed (renamed from 'error' which is reserved)
    warning, // Should be addressed
    info, // Informational
    hint, // Suggestion
};

/// Sources from which constraints can be extracted
pub const ConstraintSource = enum {
    AST_Pattern, // Extracted from AST analysis
    Type_System, // From type annotations and inference
    Control_Flow, // From control flow analysis
    Data_Flow, // From data flow analysis
    Test_Mining, // Extracted from test code
    Documentation, // From docs and comments
    Telemetry, // From runtime metrics
    User_Defined, // Manually specified
    LLM_Analysis, // Generated by LLM analysis
};

/// Types of enforcement for constraints
pub const EnforcementType = enum {
    Syntactic, // Enforced at syntax level
    Structural, // Enforced at structure level
    Semantic, // Enforced at semantic level
    Performance, // Enforced for performance requirements
    Security, // Enforced for security requirements
};

/// Priority levels for constraint resolution
pub const ConstraintPriority = enum {
    Low,
    Medium,
    High,
    Critical,

    pub fn toNumeric(self: ConstraintPriority) u32 {
        return switch (self) {
            .Low => 0,
            .Medium => 1,
            .High => 2,
            .Critical => 3,
        };
    }
};

/// A single constraint that can be validated
pub const Constraint = struct {
    /// Unique identifier (auto-generated if not specified)
    id: ConstraintID = 0,

    /// Human-readable name
    name: []const u8,

    /// Detailed description
    description: []const u8,

    /// Category of constraint
    kind: ConstraintKind,

    /// Source of constraint
    source: ConstraintSource = .AST_Pattern,

    /// Type of enforcement (inferred from kind if not specified)
    enforcement: EnforcementType = .Syntactic,

    /// Priority for conflict resolution
    priority: ConstraintPriority = .Medium,

    /// Confidence level (0.0 to 1.0)
    confidence: f32 = 1.0,

    /// Frequency of occurrence in codebase
    frequency: u32 = 1,

    /// Severity level
    severity: Severity,

    // Provenance information
    origin_file: ?[]const u8 = null,
    origin_line: ?u32 = null,
    created_at: i64 = 0,

    // Function pointers for constraint operations (typed holes)
    validate: ?*const fn (token: []const u8) bool = null,
    compile_fn: ?*const fn (self: *const Constraint) ConstraintIR = null,

    /// Initialize a new constraint with required fields
    pub fn init(
        id: ConstraintID,
        name: []const u8,
        description: []const u8,
    ) Constraint {
        return .{
            .id = id,
            .name = name,
            .description = description,
            .kind = .syntactic,
            .source = .AST_Pattern,
            .enforcement = .Syntactic,
            .priority = .Medium,
            .confidence = 1.0,
            .frequency = 1,
            .severity = .err,
            .created_at = std.time.timestamp(),
        };
    }

    /// Validate the constraint's internal consistency
    pub fn isValid(self: *const Constraint) bool {
        // Check confidence is in valid range
        if (self.confidence < 0.0 or self.confidence > 1.0) {
            return false;
        }

        // Check name is not empty
        if (self.name.len == 0) {
            return false;
        }

        // Check enforcement type matches kind
        const valid_enforcement = switch (self.kind) {
            .syntactic => self.enforcement == .Syntactic,
            .type_safety => self.enforcement == .Structural or self.enforcement == .Semantic,
            .semantic => self.enforcement == .Semantic,
            .operational => self.enforcement == .Performance,
            .security => self.enforcement == .Security,
            .architectural => self.enforcement == .Structural,
        };

        return valid_enforcement;
    }

    /// Get numeric priority value for sorting
    pub fn getPriorityValue(self: *const Constraint) u32 {
        return self.priority.toNumeric();
    }

    /// Compute a content-based unique ID from the constraint's name, description, and kind.
    /// This produces a deterministic hash so the same constraint always gets the same ID.
    pub fn computeId(self: *const Constraint) ConstraintID {
        var hasher = std.hash.Wyhash.init(0);
        hasher.update(self.name);
        hasher.update(self.description);
        const kind_bytes = std.mem.asBytes(&@intFromEnum(self.kind));
        hasher.update(kind_bytes);
        return hasher.final();
    }
};

/// Rich context data for multi-domain constrained decoding.
/// Contains pre-serialized JSON matching the sglang ConstraintSpec.from_dict() format.
/// These fields seed the Type, Import, ControlFlow, and Semantic domains.
pub const RichContext = struct {
    /// JSON array of {name, params: [{name, type}], return_type, is_async}
    function_signatures_json: ?[]const u8 = null,
    /// JSON array of {name, kind, fields: [{name, type}]}
    type_bindings_json: ?[]const u8 = null,
    /// JSON array of {name, methods: [{name, params, return_type}], fields: [{name, type}]}
    class_definitions_json: ?[]const u8 = null,
    /// JSON array of {module, items: [str], is_wildcard}
    imports_json: ?[]const u8 = null,
    /// JSON object with control flow patterns: {is_async, has_generators, error_handling_style,
    /// loop_patterns, try_catch_depth, has_recursion}
    control_flow_json: ?[]const u8 = null,
    /// JSON array of semantic constraints: [{kind, expression, source}]
    semantic_constraints_json: ?[]const u8 = null,
    /// JSON object with cross-file scope bindings from Homer's scope graph:
    /// {bindings: [{name, kind, qualified_type, definition_file}],
    ///  enclosing_scope: {name, kind, file}, canonical_imports: [...]}
    scope_bindings_json: ?[]const u8 = null,
    /// JSON object with call graph context from Homer (InlineCoder-style):
    /// {target_function, callers: [{name, file, arguments, result_usage}],
    ///  callees: [{name, file, params, return_type, is_async}]}
    call_graph_json: ?[]const u8 = null,

    pub fn deinit(self: *RichContext, allocator: std.mem.Allocator) void {
        if (self.function_signatures_json) |s| allocator.free(s);
        if (self.type_bindings_json) |s| allocator.free(s);
        if (self.class_definitions_json) |s| allocator.free(s);
        if (self.imports_json) |s| allocator.free(s);
        if (self.control_flow_json) |s| allocator.free(s);
        if (self.semantic_constraints_json) |s| allocator.free(s);
        if (self.scope_bindings_json) |s| allocator.free(s);
        if (self.call_graph_json) |s| allocator.free(s);
    }

    pub fn clone(self: *const RichContext, allocator: std.mem.Allocator) !RichContext {
        return .{
            .function_signatures_json = if (self.function_signatures_json) |s| try allocator.dupe(u8, s) else null,
            .type_bindings_json = if (self.type_bindings_json) |s| try allocator.dupe(u8, s) else null,
            .class_definitions_json = if (self.class_definitions_json) |s| try allocator.dupe(u8, s) else null,
            .imports_json = if (self.imports_json) |s| try allocator.dupe(u8, s) else null,
            .control_flow_json = if (self.control_flow_json) |s| try allocator.dupe(u8, s) else null,
            .semantic_constraints_json = if (self.semantic_constraints_json) |s| try allocator.dupe(u8, s) else null,
            .scope_bindings_json = if (self.scope_bindings_json) |s| try allocator.dupe(u8, s) else null,
            .call_graph_json = if (self.call_graph_json) |s| try allocator.dupe(u8, s) else null,
        };
    }

    /// Returns true if any context field is populated
    pub fn hasData(self: *const RichContext) bool {
        return self.function_signatures_json != null or
            self.type_bindings_json != null or
            self.class_definitions_json != null or
            self.imports_json != null or
            self.control_flow_json != null or
            self.semantic_constraints_json != null or
            self.scope_bindings_json != null or
            self.call_graph_json != null;
    }
};

/// Compiled constraint representation for efficient validation
pub const ConstraintIR = struct {
    /// JSON Schema for structured constraints
    json_schema: ?JsonSchema = null,

    /// Context-free grammar for syntax constraints
    grammar: ?Grammar = null,

    /// Regular expression patterns
    regex_patterns: []const Regex = &.{},

    /// Direct token masking rules
    token_masks: ?TokenMaskRules = null,

    /// Type inhabitation data for progressive typed generation
    type_inhabitation: ?TypeInhabitationData = null,

    /// Priority for conflict resolution
    priority: u32 = 0,

    /// true if this IR owns grammar strings (from clone), false if borrowed from interner
    owns_grammar_strings: bool = false,

    /// Hole specifications for progressive refinement
    hole_specs: []const HoleSpec = &.{},

    /// Whether this IR supports iterative refinement
    supports_refinement: bool = false,

    /// Rich context for multi-domain constrained decoding (sglang)
    rich_context: ?RichContext = null,

    /// Feasibility score (0.0 = loose, 1.0 = very tight). Set by Braid during compilation.
    feasibility_score: f32 = 0.0,

    /// Whether the constraint set was found to be feasible during compilation.
    is_feasible: bool = true,

    /// Free all allocated memory in this ConstraintIR
    pub fn deinit(self: *ConstraintIR, allocator: std.mem.Allocator) void {
        // Free json_schema if present
        if (self.json_schema) |*schema| {
            // Free the type string
            allocator.free(schema.type);

            // Free the properties ObjectMap
            if (schema.properties) |*props| {
                var iter = props.iterator();
                while (iter.next()) |entry| {
                    allocator.free(entry.key_ptr.*);
                    freeJsonValue(allocator, entry.value_ptr.*);
                }
                // Free the HashMap's backing storage
                props.deinit();
            }

            // Free the required array and its strings
            for (schema.required) |req| {
                allocator.free(req);
            }
            if (schema.required.len > 0) {
                allocator.free(schema.required);
            }
        }

        // Free grammar rules if present and owned
        if (self.grammar) |grammar| {
            if (self.owns_grammar_strings) {
                // We own the strings - free them
                allocator.free(grammar.start_symbol);
                for (grammar.rules) |rule| {
                    allocator.free(rule.lhs);
                    for (rule.rhs) |rhs_item| {
                        allocator.free(rhs_item);
                    }
                    allocator.free(rule.rhs);
                }
            } else {
                // We don't own the strings (borrowed from interner) - just free slices
                for (grammar.rules) |rule| {
                    allocator.free(rule.rhs);
                }
            }
            allocator.free(grammar.rules);
        }

        // Free regex patterns if present
        for (self.regex_patterns) |pattern| {
            // Only free non-static patterns
            if (!pattern.is_static) {
                allocator.free(pattern.pattern);
                if (pattern.flags.len > 0) {
                    allocator.free(pattern.flags);
                }
            }
        }
        if (self.regex_patterns.len > 0) {
            allocator.free(self.regex_patterns);
        }

        // Free token masks if present
        if (self.token_masks) |masks| {
            if (masks.allowed_tokens) |tokens| {
                allocator.free(tokens);
            }
            if (masks.forbidden_tokens) |tokens| {
                allocator.free(tokens);
            }
        }

        // Free type inhabitation if present
        if (self.type_inhabitation) |ti| {
            if (ti.bindings.len > 0) {
                allocator.free(ti.bindings);
            }
        }

        // Free hole specs if present
        for (self.hole_specs) |spec| {
            if (spec.fill_constraints.len > 0) {
                allocator.free(spec.fill_constraints);
            }
        }
        if (self.hole_specs.len > 0) {
            allocator.free(self.hole_specs);
        }

        // Free rich context if present
        if (self.rich_context) |*rc| {
            var ctx = rc.*;
            ctx.deinit(allocator);
        }
    }

    /// Create a deep clone of this ConstraintIR with independent ownership.
    /// Caller owns the returned ConstraintIR and must call deinit() on it.
    pub fn clone(self: *const ConstraintIR, allocator: std.mem.Allocator) !ConstraintIR {
        var cloned = ConstraintIR{
            .priority = self.priority,
            .owns_grammar_strings = true, // cloned IR owns its own strings
            .feasibility_score = self.feasibility_score,
            .is_feasible = self.is_feasible,
        };

        // Clone json_schema if present
        if (self.json_schema) |schema| {
            cloned.json_schema = try cloneJsonSchema(allocator, schema);
        }

        // Clone grammar if present
        if (self.grammar) |grammar| {
            cloned.grammar = try cloneGrammar(allocator, grammar);
        }

        // Clone regex_patterns array
        if (self.regex_patterns.len > 0) {
            const patterns = try allocator.alloc(Regex, self.regex_patterns.len);
            for (self.regex_patterns, 0..) |pattern, i| {
                if (pattern.is_static) {
                    // Static patterns: just copy the pointer, don't duplicate
                    patterns[i] = .{
                        .pattern = pattern.pattern,
                        .flags = pattern.flags,
                        .is_static = true,
                    };
                } else {
                    // Non-static patterns: duplicate the strings
                    patterns[i] = .{
                        .pattern = try allocator.dupe(u8, pattern.pattern),
                        .flags = try allocator.dupe(u8, pattern.flags),
                        .is_static = false,
                    };
                }
            }
            cloned.regex_patterns = patterns;
        }

        // Clone token_masks if present
        if (self.token_masks) |masks| {
            cloned.token_masks = try cloneTokenMasks(allocator, masks);
        }

        // Clone rich_context if present
        if (self.rich_context) |*rc| {
            cloned.rich_context = try rc.clone(allocator);
        }

        return cloned;
    }
};

/// Reference-counted wrapper for ConstraintIR enabling copy-on-write semantics.
/// This provides O(1) cache hits by avoiding deep clones on every access.
pub const SharedConstraintIR = struct {
    ir: ConstraintIR,
    ref_count: std.atomic.Value(u32),
    allocator: std.mem.Allocator,

    /// Create a new SharedConstraintIR wrapping the given IR.
    /// Takes ownership of the IR - caller should not use or free it after this.
    pub fn create(allocator: std.mem.Allocator, ir: ConstraintIR) !*SharedConstraintIR {
        const self = try allocator.create(SharedConstraintIR);
        self.* = .{
            .ir = ir,
            .ref_count = std.atomic.Value(u32).init(1),
            .allocator = allocator,
        };
        return self;
    }

    /// Acquire a reference to this SharedConstraintIR.
    /// Increments the reference count atomically.
    pub fn acquire(self: *SharedConstraintIR) *SharedConstraintIR {
        _ = self.ref_count.fetchAdd(1, .monotonic);
        return self;
    }

    /// Release a reference to this SharedConstraintIR.
    /// When the last reference is released, the IR and wrapper are freed.
    pub fn release(self: *SharedConstraintIR) void {
        // release ensures code before release() happens-before the count is decremented
        if (self.ref_count.fetchSub(1, .release) == 1) {
            // seeing 1 in the counter means other release()s have happened,
            // but it doesn't mean uses before each release() are visible.
            // The load acquires the release-sequence created by previous release()s
            // to ensure visibility of uses before dropping.
            _ = self.ref_count.load(.acquire);
            var ir = self.ir;
            ir.deinit(self.allocator);
            self.allocator.destroy(self);
        }
    }

    /// Get the current reference count (for debugging/testing).
    pub fn getRefCount(self: *const SharedConstraintIR) u32 {
        return self.ref_count.load(.monotonic);
    }

    /// Create a deep clone with its own reference count of 1.
    /// Use this when you need to modify the IR independently.
    pub fn cloneDeep(self: *const SharedConstraintIR) !*SharedConstraintIR {
        const cloned_ir = try self.ir.clone(self.allocator);
        return try SharedConstraintIR.create(self.allocator, cloned_ir);
    }
};

/// Helper function to clone JsonSchema
pub fn cloneJsonSchema(allocator: std.mem.Allocator, schema: JsonSchema) !JsonSchema {
    var cloned = JsonSchema{
        .type = try allocator.dupe(u8, schema.type),
        .additional_properties = schema.additional_properties,
    };

    // Clone properties if present
    if (schema.properties) |props| {
        var cloned_props = std.json.ObjectMap.init(allocator);
        var iter = props.iterator();
        while (iter.next()) |entry| {
            const key = try allocator.dupe(u8, entry.key_ptr.*);
            const value = try cloneJsonValue(allocator, entry.value_ptr.*);
            try cloned_props.put(key, value);
        }
        cloned.properties = cloned_props;
    }

    // Clone required array
    if (schema.required.len > 0) {
        const required = try allocator.alloc([]const u8, schema.required.len);
        for (schema.required, 0..) |req, i| {
            required[i] = try allocator.dupe(u8, req);
        }
        cloned.required = required;
    }

    return cloned;
}

/// Helper function to clone a JSON value
pub fn cloneJsonValue(allocator: std.mem.Allocator, value: std.json.Value) !std.json.Value {
    return switch (value) {
        .null => .null,
        .bool => |b| .{ .bool = b },
        .integer => |i| .{ .integer = i },
        .float => |f| .{ .float = f },
        .number_string => |s| .{ .number_string = try allocator.dupe(u8, s) },
        .string => |s| .{ .string = try allocator.dupe(u8, s) },
        .array => |arr| {
            var cloned_arr = std.json.Array.init(allocator);
            for (arr.items) |item| {
                try cloned_arr.append(try cloneJsonValue(allocator, item));
            }
            return .{ .array = cloned_arr };
        },
        .object => |obj| {
            var cloned_obj = std.json.ObjectMap.init(allocator);
            var iter = obj.iterator();
            while (iter.next()) |entry| {
                const key = try allocator.dupe(u8, entry.key_ptr.*);
                const val = try cloneJsonValue(allocator, entry.value_ptr.*);
                try cloned_obj.put(key, val);
            }
            return .{ .object = cloned_obj };
        },
    };
}

/// Helper function to free a JSON value recursively
fn freeJsonValue(allocator: std.mem.Allocator, value: std.json.Value) void {
    switch (value) {
        .null, .bool, .integer, .float => {}, // No allocation
        .number_string => |s| allocator.free(s),
        .string => |s| allocator.free(s),
        .array => |arr| {
            for (arr.items) |item| {
                freeJsonValue(allocator, item);
            }
            // Note: arr.deinit() would free the ArrayList backing storage,
            // but we're managing memory manually here
        },
        .object => |obj| {
            var iter = obj.iterator();
            while (iter.next()) |entry| {
                allocator.free(entry.key_ptr.*);
                freeJsonValue(allocator, entry.value_ptr.*);
            }
            // Note: obj.deinit() would free the HashMap backing storage,
            // but we're managing memory manually here
        },
    }
}

/// Helper function to clone Grammar
pub fn cloneGrammar(allocator: std.mem.Allocator, grammar: Grammar) !Grammar {
    const rules = try allocator.alloc(GrammarRule, grammar.rules.len);

    for (grammar.rules, 0..) |rule, i| {
        const lhs = try allocator.dupe(u8, rule.lhs);

        const rhs = try allocator.alloc([]const u8, rule.rhs.len);
        for (rule.rhs, 0..) |rhs_item, j| {
            rhs[j] = try allocator.dupe(u8, rhs_item);
        }

        rules[i] = .{
            .lhs = lhs,
            .rhs = rhs,
        };
    }

    return Grammar{
        .rules = rules,
        .start_symbol = try allocator.dupe(u8, grammar.start_symbol),
    };
}

/// Helper function to clone TokenMaskRules
fn cloneTokenMasks(allocator: std.mem.Allocator, masks: TokenMaskRules) !TokenMaskRules {
    var cloned = TokenMaskRules{
        .min_tokens = masks.min_tokens,
        .max_tokens = masks.max_tokens,
        .min_characters = masks.min_characters,
        .max_characters = masks.max_characters,
    };

    if (masks.allowed_tokens) |tokens| {
        const allowed = try allocator.alloc(u32, tokens.len);
        @memcpy(allowed, tokens);
        cloned.allowed_tokens = allowed;
    }

    if (masks.forbidden_tokens) |tokens| {
        const forbidden = try allocator.alloc(u32, tokens.len);
        @memcpy(forbidden, tokens);
        cloned.forbidden_tokens = forbidden;
    }

    return cloned;
}

/// JSON Schema representation
pub const JsonSchema = struct {
    type: []const u8,
    properties: ?std.json.ObjectMap = null,
    required: []const []const u8 = &.{},
    additional_properties: bool = true,
};

/// Context-free grammar
pub const Grammar = struct {
    rules: []const GrammarRule,
    start_symbol: []const u8,
};

pub const GrammarRule = struct {
    lhs: []const u8,
    rhs: []const []const u8,
    /// When true, this rule is optional and can produce epsilon (empty string).
    /// Grammar consumers should interpret is_optional=true as: the rule can
    /// either produce the rhs OR produce nothing (epsilon).
    is_optional: bool = false,
};

/// Regular expression pattern
pub const Regex = struct {
    pattern: []const u8,
    flags: []const u8 = "",
    is_static: bool = false, // true if pattern points to static RegexPatternPool constant
};

/// Specification for filling a hole
pub const HoleSpec = struct {
    hole_id: u64,
    fill_schema: ?JsonSchema = null,
    fill_grammar: ?Grammar = null,
    fill_patterns: []const Regex = &.{},
    fill_constraints: []const FillConstraint = &.{},
    grammar_ref: ?[]const u8 = null,
};

pub const FillConstraint = struct {
    kind: FillConstraintKind,
    value: []const u8,
    error_message: ?[]const u8 = null,
};

pub const FillConstraintKind = enum {
    must_have_type,
    must_use_binding,
    must_not_use_binding,
    must_satisfy_predicate,
    must_match_pattern,
    must_be_pure,
    must_terminate,
};

/// Individual token mask rule
pub const TokenMaskRule = struct {
    mask_type: MaskType,
    pattern: []const u8,
    description: []const u8,

    pub const MaskType = enum {
        allow_tokens,
        deny_tokens,
        require_tokens,
    };
};

/// Token masking rules for llguidance
pub const TokenMaskRules = struct {
    allowed_tokens: ?[]const u32 = null,
    forbidden_tokens: ?[]const u32 = null,
    /// Minimum number of tokens required in generated output
    min_tokens: ?u32 = null,
    /// Maximum number of tokens allowed in generated output
    max_tokens: ?u32 = null,
    /// Minimum number of characters required in generated output
    min_characters: ?usize = null,
    /// Maximum number of characters allowed in generated output
    max_characters: ?usize = null,

    /// Apply mask to token probabilities
    pub fn apply(self: TokenMaskRules, logits: []f32) void {
        if (self.forbidden_tokens) |forbidden| {
            for (forbidden) |token_id| {
                logits[token_id] = -std.math.inf(f32);
            }
        }

        if (self.allowed_tokens) |allowed| {
            // Set all non-allowed tokens to -inf
            for (logits, 0..) |*logit, i| {
                var is_allowed = false;
                for (allowed) |token_id| {
                    if (i == token_id) {
                        is_allowed = true;
                        break;
                    }
                }
                if (!is_allowed) {
                    logit.* = -std.math.inf(f32);
                }
            }
        }
    }
};

/// Language enum for type inhabitation
pub const TypeLanguage = enum {
    typescript,
    javascript,
    python,
    rust,
    go,
    java,
    cpp,
    csharp,
    kotlin,
    zig_lang,
};

/// Binding information for type inhabitation
pub const TypeBinding = struct {
    name: []const u8,
    type_sig: []const u8,
};

/// Type inhabitation data for progressive typed generation.
/// This allows constrained generation to ensure expressions match expected types.
pub const TypeInhabitationData = struct {
    /// The goal type that generated code must satisfy
    goal_type: []const u8,

    /// Current partial type (updated during generation)
    current_type: ?[]const u8 = null,

    /// Available bindings in scope
    bindings: []const TypeBinding = &.{},

    /// Pre-computed token mask for current state
    token_mask: ?TokenMaskRules = null,

    /// Language for type syntax interpretation
    language: TypeLanguage = .typescript,

    /// Serialize to JSON for FFI transmission
    pub fn toJson(self: *const TypeInhabitationData, allocator: std.mem.Allocator) ![]u8 {
        var json = std.ArrayList(u8).init(allocator);
        const writer = json.writer();

        try writer.writeAll("{");
        try writer.print("\"goal_type\":\"{s}\"", .{self.goal_type});

        if (self.current_type) |ct| {
            try writer.print(",\"current_type\":\"{s}\"", .{ct});
        }

        try writer.writeAll(",\"bindings\":[");
        for (self.bindings, 0..) |binding, i| {
            if (i > 0) try writer.writeAll(",");
            try writer.print("{{\"name\":\"{s}\",\"type\":\"{s}\"}}", .{ binding.name, binding.type_sig });
        }
        try writer.writeAll("]");

        try writer.print(",\"language\":\"{s}\"", .{@tagName(self.language)});
        try writer.writeAll("}");

        return json.toOwnedSlice();
    }
};

/// Fingerprint for tracking constraint changes in incremental compilation
pub const ConstraintFingerprint = struct {
    /// Content hash of the constraint
    hash: u64,
    /// When the constraint was first created
    created_at: i64,
    /// When the constraint was last modified
    modified_at: i64,

    /// Compute a fingerprint from a constraint's content
    pub fn compute(constraint: *const Constraint) ConstraintFingerprint {
        var hasher = std.hash.Wyhash.init(0);

        // Hash all relevant fields that affect compilation
        hasher.update(constraint.name);
        hasher.update(constraint.description);

        const kind_bytes = std.mem.asBytes(&@intFromEnum(constraint.kind));
        hasher.update(kind_bytes);

        const source_bytes = std.mem.asBytes(&@intFromEnum(constraint.source));
        hasher.update(source_bytes);

        const enforcement_bytes = std.mem.asBytes(&@intFromEnum(constraint.enforcement));
        hasher.update(enforcement_bytes);

        const priority_bytes = std.mem.asBytes(&constraint.priority.toNumeric());
        hasher.update(priority_bytes);

        const severity_bytes = std.mem.asBytes(&@intFromEnum(constraint.severity));
        hasher.update(severity_bytes);

        return .{
            .hash = hasher.final(),
            .created_at = constraint.created_at,
            .modified_at = std.time.timestamp(),
        };
    }

    /// Check if this fingerprint differs from another
    pub fn hasChanged(self: ConstraintFingerprint, other: ConstraintFingerprint) bool {
        return self.hash != other.hash;
    }
};

/// A collection of constraints
pub const ConstraintSet = struct {
    constraints: std.ArrayList(Constraint),
    name: []const u8,
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator, name: []const u8) ConstraintSet {
        return .{
            .constraints = std.ArrayList(Constraint){},
            .name = name,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *ConstraintSet) void {
        // Note: Currently does not free individual constraint string fields
        // This is intentional - constraints may use static string literals (from Clew)
        // or allocated strings (from JSON parsing). For JSON-parsed constraints,
        // use an arena allocator that gets freed separately.
        self.constraints.deinit(self.allocator);
    }

    pub fn add(self: *ConstraintSet, c: Constraint) !void {
        var constraint = c;
        // Auto-assign a content-based ID if none was explicitly set
        if (constraint.id == 0) {
            constraint.id = constraint.computeId();
        }
        try self.constraints.append(self.allocator, constraint);
    }

    /// Clone this ConstraintSet, creating a deep copy with independent ownership.
    /// All string fields (name, description, origin_file) are duplicated so the
    /// clone is fully independent of the original's allocator.
    pub fn clone(self: *const ConstraintSet, allocator: std.mem.Allocator) !ConstraintSet {
        // Deep copy the set name
        const owned_name = try allocator.dupe(u8, self.name);
        errdefer allocator.free(owned_name);

        var cloned = ConstraintSet.init(allocator, owned_name);

        // Deep copy all constraints including their string fields
        for (self.constraints.items) |constraint| {
            var c = constraint;
            c.name = try allocator.dupe(u8, constraint.name);
            c.description = try allocator.dupe(u8, constraint.description);
            if (constraint.origin_file) |file| {
                c.origin_file = try allocator.dupe(u8, file);
            }
            try cloned.constraints.append(allocator, c);
        }

        return cloned;
    }
};
