# Homebrew Formula for Ananke
# This is a template - actual releases will be generated by GitHub Actions

class Ananke < Formula
  desc "Constraint-driven code generation system"
  homepage "https://github.com/ananke-project/ananke"
  version "0.1.0"
  license "MIT OR Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ananke-project/ananke/releases/download/v0.1.0/ananke-v0.1.0-macos-x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_X86_64"
    elsif Hardware::CPU.arm?
      url "https://github.com/ananke-project/ananke/releases/download/v0.1.0/ananke-v0.1.0-macos-aarch64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_AARCH64"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ananke-project/ananke/releases/download/v0.1.0/ananke-v0.1.0-linux-x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX"
    end
  end

  def install
    # Extract the nested directory structure
    prefix.install Dir["ananke-v#{version}-*/*"]
  end

  test do
    assert_match "Ananke v", shell_output("#{bin}/ananke --version")
  end

  def caveats
    <<~EOS
      Ananke has been installed!

      Get started:
        ananke help

      Extract constraints from code:
        ananke extract src/main.ts

      Compile constraints:
        ananke compile constraints.json

      Generate constrained code:
        ananke generate "create auth handler" --constraints rules.yaml

      Configuration:
        export MODAL_ENDPOINT="https://your-inference-service.modal.run"
        export MODAL_API_KEY="your-api-key"

      Documentation:
        https://github.com/ananke-project/ananke/tree/main/docs
    EOS
  end
end
